workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Codemagic Admin"
    environment:
      xcode: 16.2
      flutter: stable
      vars:
        APP_ID: 6747345609 # <-- BURAYA KENDİ UYGULAMA ID'NİZİ YAZIN
        BUNDLE_ID: com.dyuta6.ways # <-- BURAYA KENDİ BUNDLE ID'NİZİ YAZIN

    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: List existing certificates for debugging
        script: | 
          echo "DEBUG: Listing all certificates on the Apple Developer account..."
          app-store-connect certificates
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create

      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: versioning
        script: |
          LATEST_BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
          cd ./ios
          agvtool new-version -all $(($LATEST_BUILD_NUMBER))
          agvtool new-marketing-version 1.0.$(($LATEST_BUILD_NUMBER))

      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /Users/builder/clone/build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration