workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: app_store_connect
    environment:
      xcode: 16.2
      flutter: stable
      groups:
          - app_store_connect
      vars:
        APP_ID: 6746816486
        BUNDLE_ID: com.dyuta6.ways

    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create

      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Increment version and build number
        script: |
          # App Store Connect'ten en son build numarasını almaya çalış
          if LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID" 2>/dev/null); then
            echo "Latest build number from App Store Connect: $LATEST_BUILD_NUMBER"
            NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          else
            # API başarısız olursa, timestamp kullan
            echo "Failed to get build number from App Store Connect, using timestamp"
            NEW_BUILD_NUMBER=$(date +%Y%m%d%H%M)
          fi
          
          echo "Setting new build number to: $NEW_BUILD_NUMBER"
          
          # iOS dizinine geç ve version'ları güncelle
          cd ./ios
          agvtool new-version -all $NEW_BUILD_NUMBER
          
          # Marketing version'ı yükselt - önceki approved version 1.0.20'den yüksek olmalı
          agvtool new-marketing-version 1.1.0
          
          # Güncel version bilgilerini kontrol et
          echo "Current build number: $(agvtool what-version -terse)"
          echo "Current marketing version: $(agvtool what-marketing-version -terse1)"

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /Users/builder/clone/build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        
        # Configuration related to TestFlight (optional)
        # beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
        #      - group name 1
        #      - group name 2
        
        # Configuration related to App Store (optional)
        # Note: any of the following can be omitted
        # cancel_previous_submissions: true    # Cancel previous submissions (optional)
        # release_type: MANUAL                 # Specify the release type for submissions. Default is AUTOMATIC.
        submit_to_testflight: false          # Submit build to TestFlight but not to App Store
        submit_to_app_store: true            # Submit build to App Store for review