workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: app_store_connect
    environment:
      xcode: 16.2
      flutter: stable
      groups:
          - app_store_connect
      vars:
        APP_ID: 6746816486
        BUNDLE_ID: com.dyuta6.ways

    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create

      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
          # Manual code signing fallback
          xcode-project set-automatic-code-signing \
            project-path:ios/Runner.xcodeproj \
            target:Runner \
            team-id:GCPW8WTY3S
      - name: Verify code signing setup
        script: |
          echo "=== CODE SIGNING VERIFICATION ==="
          security find-identity -v -p codesigning
          echo "================================="
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Increment version and build number
        script: |
          # iOS dizinine geç ve version'ları güncelle
          cd ./ios
          
          # Build number'ı timestamp ile oluştur (App Store için unique olmalı)
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "Setting build number to: $BUILD_NUMBER"
          
          # agvtool komutunu çalıştır ve çıktısını kontrol et
          agvtool new-version -all $BUILD_NUMBER
          
          # Marketing version'ı 1.1.4 olarak ayarla
          agvtool new-marketing-version 1.1.4
          
          # Güncel version bilgilerini kontrol et ve logla
          CURRENT_BUILD=$(agvtool what-version -terse)
          CURRENT_MARKETING=$(agvtool what-marketing-version -terse1)
          
          echo "=== VERSION INFO ==="
          echo "Build Number: $CURRENT_BUILD"
          echo "Marketing Version: $CURRENT_MARKETING"
          echo "Target Build Number: $BUILD_NUMBER"
          echo "==================="
          
          # Version bilgilerini dosyaya da yaz (debug için)
          echo "Build: $CURRENT_BUILD, Marketing: $CURRENT_MARKETING" > version_info.txt

      - name: Flutter build ipa
        script: |
          # Build öncesi kontrol
          echo "=== PRE-BUILD CHECK ==="
          flutter doctor -v
          echo "======================="
          
          # Build işlemi
          flutter build ipa --release --verbose
          
          # Build sonrası kontrol
          echo "=== BUILD ARTIFACTS ==="
          find /Users/builder/clone/build -name "*.ipa" -type f
          ls -la /Users/builder/clone/build/ios/
          echo "======================="
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /Users/builder/clone/build/ios/ipa/*.ipa
      - /Users/builder/clone/build/ios/**/*.ipa
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        
        # Configuration related to TestFlight (optional)
        # beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
        #      - group name 1
        #      - group name 2
        
        # Configuration related to App Store (optional)
        # Note: any of the following can be omitted
        # cancel_previous_submissions: true    # Cancel previous submissions (optional)
        # release_type: MANUAL                 # Specify the release type for submissions. Default is AUTOMATIC.
        submit_to_testflight: false          # Submit build to TestFlight but not to App Store
        submit_to_app_store: true            # Submit build to App Store for review