workflows:
  ios-app-store:
    name: iOS App Store Release
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: "Codemagic Admin"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.dyuta6.ways"
    scripts:
      - name: Initialize keychain
        script: | 
          keychain initialize
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create --force
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA with Flutter
        script: | 
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($BUILD_NUMBER + 1))
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        submit_to_testflight: true